name: Post Commit Log as Comment

on:
  pull_request:
    types: [closed]

jobs:
  comment-commit-history:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get recent commit messages
        id: getlog
        run: |
          echo "commits=$(git log -n 10 --pretty=format:'- %h %s')" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ PR이 병합되었습니다.

            ### 최근 커밋 목록 (참고용):
            ${{ steps.getlog.outputs.commits }}

